version: '3'

services:

  gateway:
    build:
      context: ./gateway # Assuming the gateway code is in the 'gateway' folder
    ports:
      - "8000:8000" # Exposing port 8000 to access the gateway
    environment:
      AUTH_SERVICE_URL: "http://auth_service:5000" # URL to communicate with the auth service
    depends_on:
      - auth_service

  auth_service:
    build: ./auth_service
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: auth_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DB: my_database
      MYSQL_PORT: 3306
    depends_on:
      - auth_db

  # MySQL service
  auth_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"
    volumes:
      - ./init_auth_db.sql:/docker-entrypoint-initdb.d/init_auth_db.sql # Mount the init script
      - mysql-data:/var/lib/mysql # Persist MySQL data
volumes:
  mysql-data:
networks:
  my_network:
    driver: bridge
